### ISSUE TITLE
GridSplitter not working in Android and WASM

### ISSUE THREAD

**Issue by peternary** [unoplatform/Uno.WindowsCommunityToolkit#38] opened 2019-08-29 12:53 UTC
## I'm submitting a...

- Bug report (I searched for similar issues and did not find one)

## Current behavior

Gridsplitter does not resize panels in Android or WASM

## Expected behavior

Gridsplitter could be used to resize grid panels on any platform

## Minimal reproduction of the problem with instructions
[GridsplitterSample.zip](https://github.com/unoplatform/Uno.WindowsCommunityToolkit/files/3555595/GridsplitterSample.zip)

In the attached project, attempt to resize grid in UWP, Android, and WASM.  Grid resize only works in UWP (have not tested iOS)

## Environment

```
Nuget Package(s): 
Uno.UI
Uno.Microsoft.Toolkit.Uwp.UI.Controls
Package Version(s): 
1.46.214-dev.2589
5.1.0-build.200.gf9c311b069

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (build number: )
18362
App min and target version:
- [x] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [x] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )

```

**Comment by ghuntley** [comment] 2019-09-26 20:16
Thanks for attaching the repro @peternary. Digging in and having a look at this now.

**Comment by ghuntley** [comment] 2019-09-30 19:07
howdy 👋 @peternary. Confirming that above is reproducible.

Pointer events and touch handling is currently being re-worked over at https://github.com/unoplatform/uno/pull/1256 and will be a dependency to resolving this problem.

Azure Devops is configured to publish build artifacts from [#1256](https://github.com/unoplatform/uno/pull/1256) to `https://pkgs.dev.azure.com/uno-platform/Uno Platform/_packaging/Features/nuget/v3/index.json` as  `<PackageReference Include="Uno.UI" Version="2.1.0-feature.iosTouches.2760" />` (and up)

GridSplitter with the latest version from that branch (`2.1.0-feature.iosTouches.276`) does not currently work. Digging in deeper to find out what is going on.

**Comment by ghuntley** [comment] 2019-10-04 16:48
Confirming that the two events needed by GridSplitter aren't yet emitted in https://github.com/unoplatform/uno/pull/1256. Have spoken with @dr1rrb and they are on his radar.

**Comment by DierkDroth** [comment] 2019-10-22 14:09
@ghuntley now since unoplatform/uno#1256 is merged: could the work be resumed on that issue?

**Comment by jeromelaban** [comment] 2019-10-23 13:16
@DierkDroth we've been making modifications in Uno that are related indirectly to this issue based on the changes of unoplatform/uno#1256, as it was a very large update. There's still work to do to support manipulation events in `Control` (https://github.com/unoplatform/uno/issues/1940).

We'll be updating you once we know more, thank you very much for your patience.

**Comment by DierkDroth** [comment] 2019-10-23 14:10
@jeromelaban thx for the update

**Comment by dr1rrb** [comment] 2019-11-08 21:05
The manipulation events are now [implemented](https://github.com/unoplatform/uno/pull/2046) and the `GridSplitter` is working on all platforms starting from [2.0.512-dev.3803](https://www.nuget.org/packages/Uno.UI/2.0.512-dev.3803).

I close this issue, feel free to re-open it if you encounter any issue.

**Closed as completed by dr1rrb** 2019-11-08 21:05 UTC

**Comment by DierkDroth** [comment] 2019-11-09 10:40
Thanks for taking care
